language: php

php:
  - 7.2

script:
  - composer install --dev
  - bin/console
  - bin/build

deploy:
  provider: releases
  api_key:
    secure: xaCvkjMBfvPxKKoo++/sKRzOjidVQS0zTw1Dk26C8lkSisTRYBm3KGCJaV7F9echxGaDZT5nNtUkS1fcwgibJPSG0v4THdkNmR3BxPGB0uaaHvdb+P+yazXPx8EpwoyyAJ3fXMeVxH7vmHdQPEbmDtUeGPlzkTg1zjvDt6p/Oe1Ox2m5nuNTiO+P8sQLemH6CZH7GYFJ6uF9wBUq4CtFJgTzbYBYfiiz7fP3TQR7bOZWqDENDwN7KgzFHQ7pDsjV9E6kudKmx9vPkeRj1kyRXf6UP1JVLabftRbAaRGiJ2r7xpNkmAGhhMEdS+w0z1iI6xG/NAw/43nqEiNlgUYHZmnF0uIkABvwehzZ1SpIAJ+uYbO/KdYfeGzK2LfkXWd9PEQAGMukXuFbYy3fB1JHUrIXjlQCoZSug+uxQIj02jBtINx1kEkywR7X1z2c4KKN1sWW0zmxJtb98Ej1OOXyKkosCipBs5UadGE3yRAU9CYPAcPTPDTNwYpg0Bt9qWFxQZEvIii4jHayQrwT1HG44rAU2sLrvN8vtc81KZVoavUVFhXf7ZlKLd9lkIZNe6/1efOA/h9Aw8kK4nq8KxJ1F/EfkWh7q+kmG7WD3T491YvlG+yPqoSmnAegIR5TyS6xTmysIqxmGceLleu4r8IPIK4Pk1rtqycsQvDI6fWSX90=
  file: imap-tester.phar
  skip_cleanup: true
  on:
    tags: true
